title: Pocketframe
description: Pocketframe is a lightweight yet powerful PHP framework designed to simplify modern web application development. With its intuitive structure, elegant syntax, and modular approach, Pocketframe helps developers build scalable, high-performance applications effortlessly.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
color-scheme: auto/light/dark
# logo: /public/images/logo/pocketframe.png
favicon: true
baseurl: "/docs"
