title: Pocketframe
description: Pocketframe is a lightweight yet powerful PHP framework designed to simplify modern web application development. With its intuitive structure, elegant syntax, and modular approach, Pocketframe helps developers build scalable, high-performance applications effortlessly.
show_downloads: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme
color-scheme: auto/light/dark
logo: /public/images/logo/pocketframe.png
favicon: true
